sudo: required
language: bash

before_install:
        - sudo apt-get update -q
        - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
        - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
        - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
        - /usr/bin/shellcheck --version

        - wget "https://c4pr1c3.github.io/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z"
        - sudo apt install p7zip-full
        - 7z x web_log.tsv.7z
script:

         - ls -l
         - bash test-3.sh
         - ls -l
        - pwd




notifications:
          email:
                  on_success: never